FROM python:2.7

# First get our library dependencies. This will install GEOS, gdal etc.
RUN apt-get update
RUN apt-get install binutils libproj-dev gdal-bin -y

# Now python dependencies
RUN pip install --upgrade pip

# Get the python requirements file and load it using pip
COPY ./requirements.txt /tmp/
WORKDIR /usr/src/app
RUN pip --timeout=120 install -r /tmp/requirements.txt
RUN pip install --upgrade numpy scipy pandas

